
version: "3.7"

services:
  app1:
    build: app1
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend


  app2:
    build: app2
    networks:
      - backend


networks:
  frontend:
    internal: false
  backend:
    internal: true