
version: "3.7"

services:
  app1:
    build: app1
    volumes:
      - "./app1/target:/app"
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

    restart: unless-stopped
    

  app2:
    build: app2
    networks:
      - backend


networks:
  frontend:
    internal: false
  backend:
    internal: true