name: Build and Release


on:
  push:
    branches: "patch"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }}

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/server-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build with Maven and Sign JAR
        env:
          KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        run: |
            mvn -B package --file app1/pom.xml 
   
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            app1/target/vulnapp-0.0.1-SNAPSHOT.jar

 
