name: Build and Release


on: workflow_dispatch


jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file app1/pom.xml
   
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            app1/target/vulnapp-0.0.1-SNAPSHOT.jar

 
